server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  
  location / {
    try_files $uri $uri/ /index.html;
  }
  
  location /archivos/ {
    add_header Content-Disposition "attachment";
    add_header X-Content-Type-Options "nosniff";
  }
  
  location ~* \.(xlsx|docx)$ {
    add_header Cache-Control "public, max-age=86400";
  }
  
  gzip on;
  gzip_types text/css application/javascript;
}